blog/urls.py
# coding: utf-8
"""
@author: sunxianpeng
@file: urls.py
@time: 2017/5/24 0:05

注意：在项目根目录的 blogproject\ 目录下
（即 settings.py 所在的目录），原本就有一
个 urls.py 文件，这是整个工程项目的 URL 配置文件。
而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。
这个文件将用于 blog 应用相关的 URL 配置。不要把两个
文件搞混了。
还差最后一步了，我们前面建立了一个 urls.py 文件，
并且绑定了 URL 和视图函数 index，但是 Django 并不知道。
Django 匹配 URL 模式是在 blogproject\ 目录（
即 settings.py 文件所在的目录）的 urls.py 下的，
所以我们要把 blog 应用下的 urls.py 文件包含到
blogproject\urls.py 里去，打开这个文件看到如下内容：

====
比如我们可以把文章详情页面对应的视图设计成这个样子：当用户访问
 <网站域名>/post/1/ 时，显示的是第一篇文章的内容，而当用户访问
 <网站域名>/post/2/ 时，显示的是第二篇文章的内容，这里数字代表了
 第几篇文章，也就是数据库中
 Post 记录的 id 值。下面依照这个规则来绑定 URL 和视图：

"""

from django.conf.urls import url
from . import views

urlpatterns=[
       url(r'^$',views.index,name='index'),
       url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
       url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
       url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
       url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url,include
from  blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^', include('comments.urls',namespace='comments',app_name='comments'))
]

comments/urls.py
# coding: utf-8
"""
@author: sunxianpeng
@file: urls.py
@time: 2017/5/27 22:01
"""
from django.conf.urls import url
from . import views
#别忘了给这个评论的 URL 模式规定命名空间，即 app_name = 'comments'。
amm_name='comments'

urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),

]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User#Django 自带一个用户认证系统，这个系统处理用户帐户、组、权限和基于 cookie 的 会话。本文说明这个系统是如何工作的。
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
# Create your models here.

"""
博客最主要的功能就是展示我们写的文章，它需要从某个地方获取博客文章数据才能把文章展示出来，通常来说这个地方就是数据库。
我们把写好的文章永久地保存在数据库里，当用户访问我们的博客时，Django 就去数据库里把这些数据取出来展现给用户。

博客的文章应该含有标题、正文、作者、发表时间等数据。一个更加现代化的博客文章还希望它有分类、标签、评论等。
为了更好地存储这些数据，我们需要合理地组织数据库的表结构。
我们的博客初级版本主要包含博客文章，文章会有分类以及标签。一篇文章只能有一个分类，但可以打上很多标签。
#

"""
class Category(models.Model):
    """
    分类（Category）
        Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name=models.CharField(max_length=100)
    def __unicode__(self):
        return self.name

class Tag(models.Model):
    """
    标签（Tag）
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name=models.CharField(max_length=100)
    def __unicode__(self):
        return self.name

class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    # 文章标题
    title=models.CharField(max_length=70)
    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，
    body=models.TextField()
    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    createTime=models.DateTimeField()
    modifiedTime=models.DateTimeField()
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt=models.CharField(max_length=200,blank=True)
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category=models.ForeignKey(Category)
    tags=models.ManyToManyField(Tag,blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author=models.ForeignKey(User)
    def __unicode__(self):
        return self.title
    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def  getAbsoluteUrl(self):
        """
        看到这个 reverse 函数，它的第一个参数的值是 'blog:detail'，
        意思是 blog 应用下的 name=detail 的函数，由于我们在上面通过
        app_name = 'blog' 告诉了 Django 这个 URL 模块是属于 blog 应用的，
        因此 Django 能够顺利地找到 blog 应用下 name 为 detail 的视图函数，于是
        reverse 函数会去解析这个视图函数对应的 URL，我们这里 detail 对应的规则就是
         post/(?P<pk>[0-9]+)/ 这个正则表达式，而正则表达式部分会被后面传入的参数 pk 替换，
         所以，如果 Post 的 id（或者 pk，这里 pk 和 id 是等价的） 是 255 的话，那么 get_absolute_url
          函数返回的就是 /post/255/ ，这样 Post 自己就生成了自己的 URL。
        """
        return reverse('blog:detail',kwargs={'pk':self.pk})
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag
import markdown
from comments.forms import CommentForm
# Create your views here.
"""
这里我们不再是直接把字符串传给 HttpResponse 了，而是调用 Django 提供的 render 函数。这个函数根据我们传入的参数来构造 HttpResponse。

我们首先把 HTTP 请求传了进去，然后 render 根据第二个参数的值 blog/index.html 找到这个模板文件并读取模板中的内容。
之后 render 根据我们传入的 context 参数的值把模板中的变量替换为我们传递的变量的值，
{{ title }} 被替换成了 context 字典中 title 对应的值，同理 {{ welcome }} 也被替换成相应的值。
"""

def index(request):
    postList=Post.objects.all().order_by('-createTime')
    #return render(request,'blog/index.html',context={'title':"我的博客首页",'welcome':"欢迎访问我的博客首页"})
    #排序依据的字段是 created_time，即文章的创建时间。- 号表示逆序，如果不加 - 则是正序。

    return render(request,'blog/index.html',context={'postList':postList})

def detail(request,pk):
    """视图函数很简单，它根据我们从 URL 捕获的文章 id（
    也就是 pk，这里 pk 和 id 是等价的）获取数据库中文章
    id 为该值的记录，然后传递给模板。注意这里我们用到了从
     django.shortcuts 模块导入的 get_object_or_404 方法，其
     作用就是当传入的 pk 对应的 Post 在数据库存在时，就返回对
     应的 post，如果不存在，
    就给用户返回一个 404 错误，表明用户请求的文章不存在。"""
    post=get_object_or_404(Post,pk=pk)
    post.body=markdown.markdown(post.body,extecsions=[
                                    'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',])
    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    commentList = post.comment_set.all()
    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'post': post,
               'form': form,
               'commentList': commentList
               }
    return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
    """归档视图"""
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request,pk):
    """分类页面的视图函数
    这里我们首先根据传入的 pk 值（也就是被访问的分类的 id 值）从数据库中获取到这个分类。get_object_or_404 函数和 detail 视图中一样，其作用是如果用户访问的分类不存在，则返回一个 404 错误页面以提示用户访问的资源不存在。然后我们通过 filter 函数过滤出了该分类下的全部文章。同样也和首页视图中一样对返回的文章列表进行了排序。
    """
    cate=get_object_or_404(Category,pk=pk)
    postList=Post.objects.filter(category=cate).order_by('-createTime')
    return render(request,'blog/index.html',context={'postList':postList})

def search(request):
    """首先我们使用 request.GET.get('q') 获取到用户提交的搜索关键词。用户通过表单提交的数据 django 为我们保存在 request.GET 里，这是一个类似于 Python 字典的对象，所以我们使用 get 方法从字典里取出键 q 对应的值，即用户的搜索关键词。这里字典的键之所以叫 q 是因为我们的表单中搜索框 input 的 name 属性的值是 q，如果修改了 name 属性的值，那么这个键的名称也要相应修改。"""
    q=request.GET.get('q')
    errorMsg=''
    if not q:
        errorMsg='请输入关键词'
        return render(request,'blog/errors.html',{'errorMsg':errorMsg})
    postList=Post.objects.filter(title__contains=q)#过滤条件是 title__icontains=q，即 title 中包含（contains）关键字 q，前缀 i 表示不区分大小写。这里 icontains 是查询表达式（Field lookups），其用法是在模型需要筛选的属性后面跟上两个下划线。
    return render(request,'blog/results.html',{'errorMsg':errorMsg,'postList':postList})

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.createdTime }}">{{ post.createdTime }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe  }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                <!-- 把友言评论系统代码放到想让评论框显示的地方 -->
                    <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
                    <script src="https://img1.cache.netease.com/f2e/tie/yun/sdk/loader.js"></script>
                    <script>
                    var cloudTieConfig = {
                      url: document.location.href,
                      sourceId: "",
                      productKey: "ec631d7ba20f4915a18cfe523fd54a5f",
                      target: "cloud-tie-wrapper"
                    };
                    var yunManualLoad = true;
                    Tie.loader("aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vcGMvbGl2ZXNjcmlwdC5odG1s", true);
                    </script>

                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
{#                        {{ form.name }}、{{ form.email }}、{{ form.url }} 等将自动渲染成表单控件，例如 <input> 控件。#}
{##}
{#{{ form.name.errors }}、{{ form.email.errors }} 等将渲染表单对应字段的错误（如果有的话），例如用户 email 格式填错了，那么 Django 会检查用户提交的 email 的格式，然后将格式错误信息保存到 errors 中，模板便将错误信息渲染显示。#}
                          <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                      {{ form.email }}
                                      {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                      {{ form.text }}
                                      {{ form.text.errors }}
                                 <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in commentList %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.createTime  }}</time>
                                <div class="text">
                                    {{ comment.text }}
                               </div>
                            </li>
                              {% empty %}
                                暂无评论
                              {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
                {% block main %}
                    {% if errorMsg %}
                        <p> {{ errorMsg }}</p>
                    {% endif %}
                {% for post in postList %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.getAbsoluteUrl }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.createdTime }}">{{ post.createdTime }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}.</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.getAbsoluteUrl }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                  <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
{#                <div class="pagination">#}
{#                    <ul>#}
{#                        <li><a href="">1</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">4</a></li>#}
{#                        <li><a href="">5</a></li>#}
{#                        <li class="current"><a href="">6</a></li>#}
{#                        <li><a href="">7</a></li>#}
{#                        <li><a href="">8</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">11</a></li>#}
{#                    </ul>#}
{#                </div>#}
           {% endblock main %}

templates/blog/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

{% for post in postList %}
  <div>
    {{ post.body }}
  </div>
{% empty %}
  <div class="no-post">
    没有搜索到符合条件的文章
  </div>
{% endfor %}
</body>
</html>