blog/urls.py
# coding: utf-8
"""
@author: sunxianpeng
@file: urls.py
@time: 2017/5/24 0:05

注意：在项目根目录的 blogproject\ 目录下
（即 settings.py 所在的目录），原本就有一
个 urls.py 文件，这是整个工程项目的 URL 配置文件。
而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。
这个文件将用于 blog 应用相关的 URL 配置。不要把两个
文件搞混了。
还差最后一步了，我们前面建立了一个 urls.py 文件，
并且绑定了 URL 和视图函数 index，但是 Django 并不知道。
Django 匹配 URL 模式是在 blogproject\ 目录（
即 settings.py 文件所在的目录）的 urls.py 下的，
所以我们要把 blog 应用下的 urls.py 文件包含到
blogproject\urls.py 里去，打开这个文件看到如下内容：

====
比如我们可以把文章详情页面对应的视图设计成这个样子：当用户访问
 <网站域名>/post/1/ 时，显示的是第一篇文章的内容，而当用户访问
 <网站域名>/post/2/ 时，显示的是第二篇文章的内容，这里数字代表了
 第几篇文章，也就是数据库中
 Post 记录的 id 值。下面依照这个规则来绑定 URL 和视图：

"""

from django.conf.urls import url
from . import views

urlpatterns=[
       url(r'^$',views.index,name='index'),
       url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
       url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
       url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
       url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url,include
from  blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^', include('comments.urls',namespace='comments',app_name='comments'))
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>sunxianpeng</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>sun</b> xianpeng</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                          {% csrf_token %}
                          <input type="search" name="q" placeholder="Search" required>
                          <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">sunxianpeng的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
            </main>
            <aside class="col-md-4">
                  {% block toc %}
                  {% endblock toc %}
                                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                          {% csrf_token %}
                          <input type="search" name="q" placeholder="Search" required>
                          <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% getRecentPosts as recentPostList  %}
                    <ul>
                        {% for post in recentPostList %}
                        <li>
                            <a href="{{ post.getAbsoluteUrl }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as dateList %}
                    <ul>
                        {% for date in dataList %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ data.year }}年{{ date.month }}月</a>
                        </li>
                            {% empty %}
                             暂无归档！
                            {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% getCategory as categoryList %}
                    <ul>
                        {% for category in categoryList %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}({{ category.num_posts }})</a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>

{#                <div class="widget widget-tag-cloud">#}
{#                    <h3 class="widget-title">标签云</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Java</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">笔记</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">文档</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">AngularJS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">CSS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">JavaScript</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Snippet</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">jQuery</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="rss">#}
{#                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#                </div>#}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">sunxianpeng的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>
<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>